Add Datasources to the Get Command
tableau/tabcmd pull request #162
Opened 2022-08-20 22:09 UTC by andyoneal

this simply adds datasources as an option for the Get command, in addition to the existing views and workbooks.

2022-08-22 18:59 UTC, jacalata commented
Code looks good. Can you add an e2e test in the e2e tests file and run it locally?

2022-08-23 19:25 UTC, andyoneal commented
Done. Tests all passed.

2022-09-01 23:14 UTC, jacalata approved these changes

2022-09-08 06:04 UTC, jacalata requested changes
=========================== short test summary info 
FAILED tests/commands/test_geturl_utils.py::GeturlTests::test_get_workbook_name
E       AttributeError: type object 'GetUrl' has no attribute 'get_workbook_name'
tests/commands/test_geturl_utils.py:46: AttributeError

FAILED tests/commands/test_run_commands.py::RunCommandsTest::test_get_workbook
        mock_args.url = "/workbooks/workbook-name"
        mock_args.filename = "filename.twbx"
>       get_url_command.GetUrl.run_command(mock_args)

tests/commands/test_run_commands.py:122: 
tabcmd/commands/datasources_and_workbooks/get_url_command.py:66: in run_command
    Errors.exit_with_error(logger, message=_("tabcmd.get.extension.not_found"))

=================== 2 failed, 184 passed, 1 skipped in 1.00s

2022-09-08 06:04 UTC, jacalata commented on tests/e2e/language_tests.py
> +        arguments = [command, file, "--datasource"]
does this option exist in delete?

2022-09-08 06:04 UTC, jacalata commented on tests/e2e/language_tests.py
> +    def _publish_ds(self, file, name):
does this command work?

2022-12-06 21:39 UTC, merged