Fixed login graceful exit bug
tableau/tabcmd pull request #41
Opened 2022-02-07 15:11 UTC by ovinis

Fixes #31

2022-02-07 21:50 UTC, jacalata commented on tabcmd/commands/auth/session.py
> +                              "again with updated credentials")
You could extract this to a standalone login_failed method

2022-02-07 21:51 UTC, jacalata requested changes

2022-02-07 21:51 UTC, jacalata commented on tabcmd/parsers/login_parser.py
> +        print("PROMPTS: ", args.prompt)
These seem like debug printlines? better to use the logger so they don't get accidentally left in :)

2022-02-10 03:46 UTC, mmuttreja-tableau commented on tabcmd/commands/auth/session.py
> +        except TSC.ServerResponseError as e:
Why are we only printing one error? can we have a default except error 


```tabcmd2 login
INFO pythontabcmd2.login_command  ========Creating a new session========
INFO pythontabcmd2.session  ==========Continuing previous session========
Traceback (most recent call last):
  File "/usr/local/bin/tabcmd2", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/pythontabcmd2/tabcmd2.py", line 9, in main
    command_context.execute_command()
  File "/usr/local/lib/python3.9/site-packages/pythontabcmd2/context.py", line 34, in execute_command
    command_strategy.run_command()
  File "/usr/local/lib/python3.9/site-packages/pythontabcmd2/commands/auth/login_command.py", line 22, in run_command
    self.create_session_login_command(self.args)
  File "/usr/local/lib/python3.9/site-packages/pythontabcmd2/commands/auth/login_command.py", line 28, in create_session_login_command
    session.create_session(args)
  File "/usr/local/lib/python3.9/site-packages/pythontabcmd2/commands/auth/session.py", line 167, in create_session
    signed_in_object = self.reuse_session()
  File "/usr/local/lib/python3.9/site-packages/pythontabcmd2/commands/auth/session.py", line 120, in reuse_session
    tableau_server = TSC.Server(self.server,
  File "/usr/local/lib/python3.9/site-packages/tableauserverclient/server/server.py", line 92, in __init__
    self.use_server_version()
  File "/usr/local/lib/python3.9/site-packages/tableauserverclient/server/server.py", line 132, in use_server_version
    self.version = self._determine_highest_version()
  File "/usr/local/lib/python3.9/site-packages/tableauserverclient/server/server.py", line 122, in _determine_highest_version
    version = self.server_info.get().rest_api_version
  File "/usr/local/lib/python3.9/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 177, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/tableauserverclient/server/endpoint/server_info_endpoint.py", line 22, in get
    server_response = self.get_unauthenticated_request(self.baseurl)
  File "/usr/local/lib/python3.9/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 100, in get_unauthenticated_request
    return self._make_request(self.parent_srv.session.get, url)
  File "/usr/local/lib/python3.9/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 69, in _make_request
    server_response = method(url, **parameters)
  File "/usr/local/lib/python3.9/site-packages/requests-2.25.1-py3.9.egg/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests-2.25.1-py3.9.egg/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.9/site-packages/requests-2.25.1-py3.9.egg/requests/sessions.py", line 456, in prepare_request
    p.prepare(
  File "/usr/local/lib/python3.9/site-packages/requests-2.25.1-py3.9.egg/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.9/site-packages/requests-2.25.1-py3.9.egg/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None/api/2.4/serverInfo': No schema supplied. Perhaps you meant http://None/api/2.4/serverInfo?
```

2022-02-18 06:42 UTC, ovinis commented
Closing this PR as Jac's new Refactoring PR (#56) fixes the login related bugs discussed here

2022-02-18 06:42 UTC, closed without merging